### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by praga** [dragoscirjan/aurelia-google-recaptcha#1]
Hi,

Could you please tell me how to use this in a project.

Cheers.

**Comment by dragoscirjan** [comment]
Hello,

We weren't planning on releasing this to the public yet, but since you've discovered it, you deserve the best answer I can provide at this moment.

I have updated the documentation. Please note that for now you can only use one recaptcha per component. I haven't tested it with multiple recaptcha tags. 

Please also instpect src/recaptcha.js to see all implemented recaptcha variables, also read Google Recaptcha documentation.

If you still have questions, I'm here to help.

**Comment by praga** [comment]
Thanks alot. The documentation is perfect
